# By default, look up the OpenStack project ID from the environment
openstack_project_id: "{{ lookup('env', 'OS_PROJECT_ID') }}"
# By default, don't run the cluster validation
cluster_run_validation: no
# By default, use a simple prefix
terraform_path_prefix: "cluster/"
