---
roles:
  - src: stackhpc.nfs
  - src: stackhpc.openhpc
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.blackbox-exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.alertmanager
  - src: cloudalchemy.grafana
  - src: geerlingguy.mysql
  - src: jriguera.configdrive
  - name: stackhpc.terraform-infra
    src: https://github.com/stackhpc/ansible-role-terraform-infra
    type: git
    version: b750fd38be4eedf111eff0ed8833295efe3b6422

collections:
  - name: ansible.posix
  - name: community.general
  - name: community.grafana
  - name: community.mysql
  - name: containers.podman
  - name: openstack.cloud
  - name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
    type: git
    version: main
