---

# Provision the infrastructure using Terraform
- name: Provision infrastructure
  hosts: openstack
  roles:
    - role: terraform_infra
      vars:
        # Variables controlling the Terraform provisioning
        terraform_project_path: "{{ playbook_dir }}/terraform"
        terraform_state: "{{ cluster_state | default('present') }}"
        terraform_variables:
          cluster_name: "{{ cluster_name }}"
          cluster_network: "{{ cluster_network }}"
          cluster_floating_ip: "{{ cluster_floating_ip }}"
          key_pair: "{{ cluster_key_pair }}"
          compute_count: "{{ compute_count }}"
          login_image: "{{ cluster_image }}"
          control_image: "{{ cluster_image }}"
          compute_image: "{{ cluster_image }}"
          login_flavor: "{{ login_flavor }}"
          control_flavor: "{{ login_flavor }}"
          compute_flavor: "{{ compute_flavor }}"

# Ensure that the secrets are generated and persisted on the control host
- name: Generate and persist secrets
  hosts: control
  gather_facts: no
  become: yes
  roles: [persist_openhpc_secrets]

# Configure the hosts as a Slurm cluster
# Use the playbooks invidually rather than the site playbook as it avoids the
# need to define the environment variables referencing an environment
- import_playbook: vendor/stackhpc/ansible-slurm-appliance/ansible/validate.yml
- import_playbook: vendor/stackhpc/ansible-slurm-appliance/ansible/bootstrap.yml
- import_playbook: vendor/stackhpc/ansible-slurm-appliance/ansible/filesystems.yml
- import_playbook: vendor/stackhpc/ansible-slurm-appliance/ansible/slurm.yml

# Temporarily, the grafana_install tag is skipped (see ansible.cfg) and we install Grafana manually here
# https://github.com/grafana/grafana/issues/36935
# TODO: REMOVE THIS
- name: Install Grafana
  hosts: grafana
  tags: grafana
  become: yes
  tasks:
    - name: Install Grafana from RPM
      yum:
        name: https://dl.grafana.com/oss/release/grafana-8.0.6-1.x86_64.rpm
        disable_gpg_check: yes
        state: present

- import_playbook: vendor/stackhpc/ansible-slurm-appliance/ansible/monitoring.yml
