# The Terraform version to install
terraform_version: 1.0.2
# Map architectures as reported by ansible_architecture to those in Terraform URLs
terraform_architectures:
  x86_64: amd64
  arm64: arm64
# The system name to use in the Terraform zip name
terraform_system: "{{ ansible_system | lower }}"
# The architecture to use in the Terraform zip name
terraform_architecture: "{{ terraform_architectures[ansible_architecture] }}"
# The name of the Terraform zip
terraform_zip_name: terraform_{{ terraform_version }}_{{ terraform_system }}_{{ terraform_architecture }}.zip
# The URL of the Terraform binary
terraform_binary_url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/{{ terraform_zip_name }}

# The directory to put the Terraform binary in
terraform_binary_directory: "{{ playbook_dir }}/.bin"
# The path to the Terraform binary
terraform_binary_path: "{{ terraform_binary_directory }}/terraform"


# The SSH user defaults to centos
cluster_ssh_user: centos
# The gateway user defaults to the regular SSH user
cluster_gateway_user: "{{ cluster_ssh_user }}"
